name: Update Metals Prices

on:
  schedule:
    - cron: '0 * * * *' # Каждый час
  workflow_dispatch: # Возможность запуска вручную

jobs:
  update_prices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install firebase-admin requests

      - name: Create Firebase key file
        run: |
          printf "%s" "${{ secrets.FIREBASE_KEY }}" > serviceAccountKey.json




      - name: Run update script
        run: python update_metals.py
        env:
          FIREBASE_KEY: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
